{% set version = "2.7" %}

package:
  name: freetype
  version: {{ version }}

source:
  url: http://download.savannah.gnu.org/releases/freetype/freetype-{{ version }}.tar.bz2
  sha256: d6a451f5b754857d2aa3964fd4473f8bc5c64e879b24516d780fb26bec7f7d48
  patches:
    # Build shared libs with msvc.
    - winshared.patch  # [win]

build:
  number: 2
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - zlib 1.2.11
    - libpng >=1.6.22,<1.6.31
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - zlib 1.2.11
    - libpng >=1.6.22,<1.6.31
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - freetype-config --version  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.freetype.org/
  license: GPL-2.0 and FreeType (http://freetype.sourceforge.net/FTL.TXT)
  summary: 'A TrueType Font Library.'

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
