travis:
  secure:
    BINSTAR_TOKEN: lvq4+O2P50PWqnpX/Q4vXd27mgDj+fJev72hd9KiMQHGwEGjIcaJyemkqYbMkRBl6LcyXqGs4Fm9rVGIJ8+zSQf9KigTRiJVDPJTsEly9NH1L0n4PfoiyERyVtKuq9nuUKGok8LwWZp2jK8ouUpvo4Egz2kGmYwHwT873RZUehKIrfvK84R8D/c8PDaEGwM2a+5EXAF3UlzOY8DWepsxHb4XSkMTl2qFxd1elcDst5UP1Vsw8bfx9Q2kuXfpB7y/uOctI7nVQltTcUq/Ta7yzJWdEHngyV2pPgwFkMysbBgLBoa6bR5qGxtqMeGW3EYQFo8kcRtXuWjxaJhNniaTgdp88t5v3rmPVQaQIVt1lQB9Ush95fgB9kXGoxKYXG3IddGvDfQagRGNTLd9k0rYvOIFqw8kyagffug3iel5xk6o2tQGfUcD79y9usYSQq7lwuO2Oo5+LJcFk1ztTYMzuAPNMkFj0Tqx1gVs5oRVmuSCDWFDTIxlTQ2eJs/bIQ9I8Hspti16bEaM3Lf60QlXIF4rs6zTDtXgOaNOkhg+FjJWL47T7PfJlx2hlB6Qk5jHyGTW35e0K5lyHXmEYWg52MWQHp0Qi5Mn7mnYvyrkbSbk9mFJA6MmClx9gXc4L5Hceo2LPmc/mWywQa4I4lLhWpwvS5N4Cr3G1UsUy1MrE3o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
